import frappe

def add_breeds():
    breeds = [
        # Dogs
        {
            "breed_name": "Labrador Retriever",
            "species": "Dog",
            "size": "Large",
            "coat_notes": "Short double coat; sheds heavily, requires regular brushing.",
            "coat_type": "Short",
            "coat_density": "Thick",
            "coat_texture": "Smooth",
            "coat_length": "Short",
            "shedding_level": "Heavy",
            "seasonal_shedding": "Yes",
            "matting_risk": "Low",
            "grooming_frequency": "Monthly",
            "brushing_needs": "Weekly",
            "trimming_needs": "No",
            "bathing_frequency": "Monthly",
            "skin_sensitivity": "Low",
            "allergy_prone": "No",
        },
        {
            "breed_name": "Golden Retriever",
            "species": "Dog",
            "size": "Large",
            "coat_notes": "Dense water-repellent coat; sheds heavily, requires regular brushing.",
            "coat_type": "Double",
            "coat_density": "Thick",
            "coat_texture": "Smooth",
            "coat_length": "Medium",
            "shedding_level": "Heavy",
            "seasonal_shedding": "Yes",
            "matting_risk": "Medium",
            "grooming_frequency": "Monthly",
            "brushing_needs": "Weekly",
            "trimming_needs": "Yes",
            "bathing_frequency": "Monthly",
            "skin_sensitivity": "Medium",
            "allergy_prone": "No",
        },
        {
            "breed_name": "Poodle",
            "species": "Dog",
            "size": "Medium",
            "coat_notes": "Curly coat; requires frequent grooming to prevent matting.",
            "coat_type": "Curly",
            "coat_density": "Normal",
            "coat_texture": "Silky",
            "coat_length": "Medium",
            "shedding_level": "Minimal",
            "seasonal_shedding": "No",
            "matting_risk": "High",
            "grooming_frequency": "Bi-Weekly",
            "brushing_needs": "Daily",
            "trimming_needs": "Yes",
            "bathing_frequency": "Monthly",
            "skin_sensitivity": "Medium",
            "allergy_prone": "Yes",
        },
        {
            "breed_name": "Beagle",
            "species": "Dog",
            "size": "Medium",
            "coat_notes": "Short coat; minimal shedding, easy to maintain.",
            "coat_type": "Short",
            "coat_density": "Normal",
            "coat_texture": "Smooth",
            "coat_length": "Short",
            "shedding_level": "Moderate",
            "seasonal_shedding": "No",
            "matting_risk": "Low",
            "grooming_frequency": "Monthly",
            "brushing_needs": "Weekly",
            "trimming_needs": "No",
            "bathing_frequency": "Bi-Monthly",
            "skin_sensitivity": "Low",
            "allergy_prone": "No",
        },
        {
            "breed_name": "Bulldog",
            "species": "Dog",
            "size": "Medium",
            "coat_notes": "Short smooth coat; minimal shedding, easy to maintain.",
            "coat_type": "Short",
            "coat_density": "Normal",
            "coat_texture": "Smooth",
            "coat_length": "Short",
            "shedding_level": "Minimal",
            "seasonal_shedding": "No",
            "matting_risk": "Low",
            "grooming_frequency": "Monthly",
            "brushing_needs": "Weekly",
            "trimming_needs": "No",
            "bathing_frequency": "Bi-Monthly",
            "skin_sensitivity": "Medium",
            "allergy_prone": "No",
        },
        {
            "breed_name": "German Shepherd",
            "species": "Dog",
            "size": "Large",
            "coat_notes": "Dense double coat; sheds heavily, requires regular de-shedding.",
            "coat_type": "Double",
            "coat_density": "Thick",
            "coat_texture": "Smooth",
            "coat_length": "Medium",
            "shedding_level": "Heavy",
            "seasonal_shedding": "Yes",
            "matting_risk": "Medium",
            "grooming_frequency": "Monthly",
            "brushing_needs": "Weekly",
            "trimming_needs": "No",
            "bathing_frequency": "Monthly",
            "skin_sensitivity": "Medium",
            "allergy_prone": "No",
        },
        {
            "breed_name": "Siberian Husky",
            "species": "Dog",
            "size": "Large",
            "coat_notes": "Thick double coat; sheds seasonally, requires regular grooming.",
            "coat_type": "Double",
            "coat_density": "Thick",
            "coat_texture": "Fluffy",
            "coat_length": "Medium",
            "shedding_level": "Heavy",
            "seasonal_shedding": "Yes",
            "matting_risk": "Medium",
            "grooming_frequency": "Monthly",
            "brushing_needs": "Weekly",
            "trimming_needs": "No",
            "bathing_frequency": "Monthly",
            "skin_sensitivity": "Low",
            "allergy_prone": "No",
        },
        {
            "breed_name": "Rottweiler",
            "species": "Dog",
            "size": "Large",
            "coat_notes": "Short coat; moderate shedding, easy to maintain.",
            "coat_type": "Short",
            "coat_density": "Normal",
            "coat_texture": "Smooth",
            "coat_length": "Short",
            "shedding_level": "Moderate",
            "seasonal_shedding": "No",
            "matting_risk": "Low",
            "grooming_frequency": "Monthly",
            "brushing_needs": "Weekly",
            "trimming_needs": "No",
            "bathing_frequency": "Monthly",
            "skin_sensitivity": "Low",
            "allergy_prone": "No",
        },
        {
            "breed_name": "Shih Tzu",
            "species": "Dog",
            "size": "Small",
            "coat_notes": "Long silky coat; prone to matting, requires frequent brushing.",
            "coat_type": "Long",
            "coat_density": "Thick",
            "coat_texture": "Silky",
            "coat_length": "Long",
            "shedding_level": "Minimal",
            "seasonal_shedding": "No",
            "matting_risk": "High",
            "grooming_frequency": "Bi-Weekly",
            "brushing_needs": "Daily",
            "trimming_needs": "Yes",
            "bathing_frequency": "Monthly",
            "skin_sensitivity": "Medium",
            "allergy_prone": "Yes",
        },
        {
            "breed_name": "Dachshund",
            "species": "Dog",
            "size": "Small",
            "coat_notes": "Smooth or long coat; moderate shedding, requires occasional grooming.",
            "coat_type": "Short",
            "coat_density": "Normal",
            "coat_texture": "Smooth",
            "coat_length": "Short",
            "shedding_level": "Moderate",
            "seasonal_shedding": "No",
            "matting_risk": "Low",
            "grooming_frequency": "Bi-Monthly",
            "brushing_needs": "Weekly",
            "trimming_needs": "No",
            "bathing_frequency": "Monthly",
            "skin_sensitivity": "Low",
            "allergy_prone": "No",
        },
        {
            "breed_name": "Chihuahua",
            "species": "Dog",
            "size": "Small",
            "coat_notes": "Short coat; minimal shedding, easy to maintain.",
            "coat_type": "Short",
            "coat_density": "Sparse",
            "coat_texture": "Smooth",
            "coat_length": "Short",
            "shedding_level": "Minimal",
            "seasonal_shedding": "No",
            "matting_risk": "Low",
            "grooming_frequency": "Monthly",
            "brushing_needs": "Weekly",
            "trimming_needs": "No",
            "bathing_frequency": "Bi-Monthly",
            "skin_sensitivity": "Low",
            "allergy_prone": "No",
        },
        {
            "breed_name": "Boxer",
            "species": "Dog",
            "size": "Medium",
            "coat_notes": "Short coat; moderate shedding, easy to maintain.",
            "coat_type": "Short",
            "coat_density": "Normal",
            "coat_texture": "Smooth",
            "coat_length": "Short",
            "shedding_level": "Moderate",
            "seasonal_shedding": "No",
            "matting_risk": "Low",
            "grooming_frequency": "Monthly",
            "brushing_needs": "Weekly",
            "trimming_needs": "No",
            "bathing_frequency": "Monthly",
            "skin_sensitivity": "Medium",
            "allergy_prone": "No",
        },
        {
            "breed_name": "Yorkshire Terrier",
            "species": "Dog",
            "size": "Small",
            "coat_notes": "Long silky coat; prone to tangling, requires regular grooming.",
            "coat_type": "Long",
            "coat_density": "Normal",
            "coat_texture": "Silky",
            "coat_length": "Long",
            "shedding_level": "Minimal",
            "seasonal_shedding": "No",
            "matting_risk": "High",
            "grooming_frequency": "Bi-Weekly",
            "brushing_needs": "Daily",
            "trimming_needs": "Yes",
            "bathing_frequency": "Monthly",
            "skin_sensitivity": "Medium",
            "allergy_prone": "Yes",
        },
        {
            "breed_name": "Great Dane",
            "species": "Dog",
            "size": "Large",
            "coat_notes": "Short smooth coat; minimal shedding, easy to maintain.",
            "coat_type": "Short",
            "coat_density": "Normal",
            "coat_texture": "Smooth",
            "coat_length": "Short",
            "shedding_level": "Minimal",
            "seasonal_shedding": "No",
            "matting_risk": "Low",
            "grooming_frequency": "Monthly",
            "brushing_needs": "Weekly",
            "trimming_needs": "No",
            "bathing_frequency": "Monthly",
            "skin_sensitivity": "Low",
            "allergy_prone": "No",
        },
        {
            "breed_name": "Border Collie",
            "species": "Dog",
            "size": "Medium",
            "coat_notes": "Medium-length coat; sheds moderately, requires regular brushing.",
            "coat_type": "Medium",
            "coat_density": "Thick",
            "coat_texture": "Smooth",
            "coat_length": "Medium",
            "shedding_level": "Moderate",
            "seasonal_shedding": "Yes",
            "matting_risk": "Medium",
            "grooming_frequency": "Monthly",
            "brushing_needs": "Weekly",
            "trimming_needs": "Yes",
            "bathing_frequency": "Monthly",
            "skin_sensitivity": "Medium",
            "allergy_prone": "No",
        },
        {
            "breed_name": "Dalmatian",
            "species": "Dog",
            "size": "Large",
            "coat_notes": "Short smooth coat; sheds heavily, easy to maintain.",
            "coat_type": "Short",
            "coat_density": "Normal",
            "coat_texture": "Smooth",
            "coat_length": "Short",
            "shedding_level": "Heavy",
            "seasonal_shedding": "Yes",
            "matting_risk": "Low",
            "grooming_frequency": "Monthly",
            "brushing_needs": "Weekly",
            "trimming_needs": "No",
            "bathing_frequency": "Monthly",
            "skin_sensitivity": "Low",
            "allergy_prone": "No",
        },
        {
            "breed_name": "Cocker Spaniel",
            "species": "Dog",
            "size": "Medium",
            "coat_notes": "Long silky coat; prone to matting, requires frequent grooming.",
            "coat_type": "Long",
            "coat_density": "Normal",
            "coat_texture": "Smooth",
            "coat_length": "Medium",
            "shedding_level": "Moderate",
            "seasonal_shedding": "Yes",
            "matting_risk": "High",
            "grooming_frequency": "Bi-Weekly",
            "brushing_needs": "Weekly",
            "trimming_needs": "Yes",
            "bathing_frequency": "Monthly",
            "skin_sensitivity": "Medium",
            "allergy_prone": "Yes",
        },
        {
            "breed_name": "St. Bernard",
            "species": "Dog",
            "size": "Large",
            "coat_notes": "Thick coat; sheds heavily, requires frequent grooming.",
            "coat_type": "Double",
            "coat_density": "Thick",
            "coat_texture": "Fluffy",
            "coat_length": "Long",
            "shedding_level": "Heavy",
            "seasonal_shedding": "Yes",
            "matting_risk": "Medium",
            "grooming_frequency": "Weekly",
            "brushing_needs": "Weekly",
            "trimming_needs": "No",
            "bathing_frequency": "Monthly",
            "skin_sensitivity": "Medium",
            "allergy_prone": "No",
        },
        {
            "breed_name": "Maltese",
            "species": "Dog",
            "size": "Small",
            "coat_notes": "Long straight coat; prone to matting, requires daily grooming.",
            "coat_type": "Long",
            "coat_density": "Normal",
            "coat_texture": "Silky",
            "coat_length": "Long",
            "shedding_level": "Minimal",
            "seasonal_shedding": "No",
            "matting_risk": "High",
            "grooming_frequency": "Weekly",
            "brushing_needs": "Daily",
            "trimming_needs": "Yes",
            "bathing_frequency": "Bi-Weekly",
            "skin_sensitivity": "High",
            "allergy_prone": "Yes",
        },

        # Cats
        {
            "breed_name": "Persian Cat",
            "species": "Cat",
            "size": "Medium",
            "coat_notes": "Long silky fur; prone to matting, requires daily brushing.",
            "coat_type": "Long",
            "coat_density": "Thick",
            "coat_texture": "Silky",
            "coat_length": "Long",
            "shedding_level": "Moderate",
            "seasonal_shedding": "Yes",
            "matting_risk": "High",
            "grooming_frequency": "Weekly",
            "brushing_needs": "Daily",
            "trimming_needs": "No",
            "bathing_frequency": "As Needed",
            "skin_sensitivity": "High",
            "allergy_prone": "Yes",
        },
        {
            "breed_name": "Maine Coon",
            "species": "Cat",
            "size": "Large",
            "coat_notes": "Thick shaggy coat; sheds moderately, requires weekly grooming.",
            "coat_type": "Long",
            "coat_density": "Thick",
            "coat_texture": "Fluffy",
            "coat_length": "Long",
            "shedding_level": "Moderate",
            "seasonal_shedding": "Yes",
            "matting_risk": "Medium",
            "grooming_frequency": "Weekly",
            "brushing_needs": "Weekly",
            "trimming_needs": "No",
            "bathing_frequency": "Monthly",
            "skin_sensitivity": "Low",
            "allergy_prone": "No",
        },
        {
            "breed_name": "Siamese",
            "species": "Cat",
            "size": "Medium",
            "coat_notes": "Short smooth coat; minimal shedding, easy to maintain.",
            "coat_type": "Short",
            "coat_density": "Sparse",
            "coat_texture": "Smooth",
            "coat_length": "Short",
            "shedding_level": "Minimal",
            "seasonal_shedding": "No",
            "matting_risk": "Low",
            "grooming_frequency": "Monthly",
            "brushing_needs": "Weekly",
            "trimming_needs": "No",
            "bathing_frequency": "As Needed",
            "skin_sensitivity": "Low",
            "allergy_prone": "No",
        },
        {
            "breed_name": "Bengal Cat",
            "species": "Cat",
            "size": "Medium",
            "coat_notes": "Short soft coat; minimal shedding, easy to maintain.",
            "coat_type": "Short",
            "coat_density": "Normal",
            "coat_texture": "Smooth",
            "coat_length": "Short",
            "shedding_level": "Minimal",
            "seasonal_shedding": "No",
            "matting_risk": "Low",
            "grooming_frequency": "Monthly",
            "brushing_needs": "Weekly",
            "trimming_needs": "No",
            "bathing_frequency": "Bi-Monthly",
            "skin_sensitivity": "Low",
            "allergy_prone": "No",
        },
        {
            "breed_name": "Ragdoll",
            "species": "Cat",
            "size": "Large",
            "coat_notes": "Semi-long silky coat; sheds moderately, requires occasional grooming.",
            "coat_type": "Long",
            "coat_density": "Normal",
            "coat_texture": "Silky",
            "coat_length": "Long",
            "shedding_level": "Moderate",
            "seasonal_shedding": "Yes",
            "matting_risk": "Medium",
            "grooming_frequency": "Bi-Monthly",
            "brushing_needs": "Weekly",
            "trimming_needs": "No",
            "bathing_frequency": "Monthly",
            "skin_sensitivity": "Medium",
            "allergy_prone": "No",
        }
    ]

    for breed in breeds:
        if not frappe.db.exists("Breed", {"breed_name": breed["breed_name"]}):
            doc = frappe.get_doc({
                "doctype": "Breed",
                "breed_name": breed["breed_name"],
                "species": breed["species"],
                "size": breed["size"],
                "coat_notes": breed["coat_notes"],
                "coat_type": breed["coat_type"],
                "coat_density": breed["coat_density"],
                "coat_texture": breed["coat_texture"],
                "coat_length": breed["coat_length"],
                "shedding_level": breed["shedding_level"],
                "seasonal_shedding": breed["seasonal_shedding"],
                "matting_risk": breed["matting_risk"],
                "grooming_frequency": breed["grooming_frequency"],
                "brushing_needs": breed["brushing_needs"],
                "trimming_needs": breed["trimming_needs"],
                "bathing_frequency": breed["bathing_frequency"],
                "skin_sensitivity": breed["skin_sensitivity"],
                "allergy_prone": breed["allergy_prone"],
                "naming_series": "BR-.#####"
            })
            doc.insert()
            frappe.db.commit()  # Commit changes to the database
            print(f"Added breed: {breed['breed_name']}")
        else:
            print(f"Breed already exists: {breed['breed_name']}")

# run the script
# add_breeds()